apiVersion: v2
name: cli-tools
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "latest"
icon: https://static.wirsindhandwerk.de/style/images/favicon/favicon-128.png
