apiVersion: v2
name: wsh-go-webservice
description: A Helm chart for Kubernetes
type: application
version: 0.2.1
appVersion: "1.0"
icon: https://static.wirsindhandwerk.de/style/images/favicon/favicon-128.png
